/**
 * GPayments 3DS Server API Reference
 * Welcome to the 3DS Server RESTful API. You can use our API to access 3DS Server functionalities.  The 3DS Server API is organised around REST. Our API has predictable, resource-oriented URLs, and uses HTTP response codes to indicate API errors. We use built-in HTTP features, such as HTTP authentication and HTTP verbs, which are understood by off-the-shelf HTTP clients. We support cross-origin resource sharing, allowing you to interact securely with our API from a dto-side web application (though you should never expose your secret API key in any public website’s dto-side code). JSON is returned by all API responses, including errors.
 * <p>
 * <p>
 * Contact: techsupport@gpayments.com
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.gpayments.requestor.dto.activeserver;

import com.fasterxml.jackson.annotation.JsonProperty;


/**
 * CardholderInformation
 */

public class CardholderInformation {
    @JsonProperty("billAddrCity")
    private String billAddrCity = null;

    @JsonProperty("billAddrCountry")
    private String billAddrCountry = null;

    @JsonProperty("billAddrLine1")
    private String billAddrLine1 = null;

    @JsonProperty("billAddrLine2")
    private String billAddrLine2 = null;

    @JsonProperty("billAddrLine3")
    private String billAddrLine3 = null;

    @JsonProperty("billAddrPostCode")
    private String billAddrPostCode = null;

    @JsonProperty("billAddrState")
    private String billAddrState = null;

    @JsonProperty("cardholderName")
    private String cardholderName = null;

    @JsonProperty("email")
    private String email = null;

    @JsonProperty("homePhone")
    private PhoneNumber homePhone = null;

    @JsonProperty("mobilePhone")
    private PhoneNumber mobilePhone = null;

    @JsonProperty("shipAddrCity")
    private String shipAddrCity = null;

    @JsonProperty("shipAddrCountry")
    private String shipAddrCountry = null;

    @JsonProperty("shipAddrLine1")
    private String shipAddrLine1 = null;

    @JsonProperty("shipAddrLine2")
    private String shipAddrLine2 = null;

    @JsonProperty("shipAddrLine3")
    private String shipAddrLine3 = null;

    @JsonProperty("shipAddrPostCode")
    private String shipAddrPostCode = null;

    @JsonProperty("shipAddrState")
    private String shipAddrState = null;

    @JsonProperty("workPhone")
    private PhoneNumber workPhone = null;


    /**
     * The city of the Cardholder billing address associated with the card used for this purchase. Length: Maximum 50 characters
     *
     * @return billAddrCity
     **/
    public String getBillAddrCity() {
        return billAddrCity;
    }

    public void setBillAddrCity(String billAddrCity) {
        this.billAddrCity = billAddrCity;
    }


    /**
     * The country of the Cardholder billing address associated with the card used for this purchase. Length: 3 characters
     *
     * @return billAddrCountry
     **/
    public String getBillAddrCountry() {
        return billAddrCountry;
    }

    public void setBillAddrCountry(String billAddrCountry) {
        this.billAddrCountry = billAddrCountry;
    }


    /**
     * First line of the street address or equivalent local portion of the Cardholder billing address associated with the card used for this purchase. Length: Maximum 50 characters
     *
     * @return billAddrLine1
     **/
    public String getBillAddrLine1() {
        return billAddrLine1;
    }

    public void setBillAddrLine1(String billAddrLine1) {
        this.billAddrLine1 = billAddrLine1;
    }


    /**
     * Second line of the street address or equivalent local portion of the Cardholder billing address associated with the card used for this purchase. Length: Maximum 50 characters
     *
     * @return billAddrLine2
     **/
    public String getBillAddrLine2() {
        return billAddrLine2;
    }

    public void setBillAddrLine2(String billAddrLine2) {
        this.billAddrLine2 = billAddrLine2;
    }


    /**
     * Third line of the street address or equivalent local portion of the Cardholder billing address associated with the card used for this purchase. Length: Maximum 50 characters
     *
     * @return billAddrLine3
     **/
    public String getBillAddrLine3() {
        return billAddrLine3;
    }

    public void setBillAddrLine3(String billAddrLine3) {
        this.billAddrLine3 = billAddrLine3;
    }

    /**
     * ZIP or other postal code of the Cardholder billing address associated with the card used for this purchase. Length: Maximum 16 characters
     *
     * @return billAddrPostCode
     **/
    public String getBillAddrPostCode() {
        return billAddrPostCode;
    }

    public void setBillAddrPostCode(String billAddrPostCode) {
        this.billAddrPostCode = billAddrPostCode;
    }


    /**
     * The state or province of the Cardholder billing address associated with the card used for this purchase.Length: Maximum 3 characters
     *
     * @return billAddrState
     **/
    public String getBillAddrState() {
        return billAddrState;
    }

    public void setBillAddrState(String billAddrState) {
        this.billAddrState = billAddrState;
    }

    /**
     * Name of the Cardholder. Length: 2–45 characters
     *
     * @return cardholderName
     **/
    public String getCardholderName() {
        return cardholderName;
    }

    public void setCardholderName(String cardholderName) {
        this.cardholderName = cardholderName;
    }


    /**
     * The email address associated with the account that is either entered by the Cardholder, or is on file with the 3DS Requestor. Length: Maximum 254 characters
     *
     * @return email
     **/
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * The home phone number provided by the Cardholder.
     *
     * @return homePhone
     **/
    public PhoneNumber getHomePhone() {
        return homePhone;
    }

    public void setHomePhone(PhoneNumber homePhone) {
        this.homePhone = homePhone;
    }


    /**
     * The mobile phone number provided by the Cardholder.
     *
     * @return mobilePhone
     **/
    public PhoneNumber getMobilePhone() {
        return mobilePhone;
    }

    public void setMobilePhone(PhoneNumber mobilePhone) {
        this.mobilePhone = mobilePhone;
    }


    /**
     * City portion of the shipping address requested by the Cardholder. Length: Maximum 50 characters
     *
     * @return shipAddrCity
     **/
    public String getShipAddrCity() {
        return shipAddrCity;
    }

    public void setShipAddrCity(String shipAddrCity) {
        this.shipAddrCity = shipAddrCity;
    }


    /**
     * Country of the shipping address requested by the Cardholder. Length: 3 characters
     *
     * @return shipAddrCountry
     **/
    public String getShipAddrCountry() {
        return shipAddrCountry;
    }

    public void setShipAddrCountry(String shipAddrCountry) {
        this.shipAddrCountry = shipAddrCountry;
    }

    /**
     * First line of the street address or equivalent local portion of the shipping address requested by the Cardholder. Length: Maximum 50 characters
     *
     * @return shipAddrLine1
     **/
    public String getShipAddrLine1() {
        return shipAddrLine1;
    }

    public void setShipAddrLine1(String shipAddrLine1) {
        this.shipAddrLine1 = shipAddrLine1;
    }

    /**
     * The second line of the street address or equivalent local portion of the shipping address requested by the Cardholder. Length: Maximum 50 characters
     *
     * @return shipAddrLine2
     **/
    public String getShipAddrLine2() {
        return shipAddrLine2;
    }

    public void setShipAddrLine2(String shipAddrLine2) {
        this.shipAddrLine2 = shipAddrLine2;
    }

    /**
     * The third line of the street address or equivalent local portion of the shipping address requested by the Cardholder. Length: Maximum 50 characters
     *
     * @return shipAddrLine3
     **/
    public String getShipAddrLine3() {
        return shipAddrLine3;
    }

    public void setShipAddrLine3(String shipAddrLine3) {
        this.shipAddrLine3 = shipAddrLine3;
    }


    /**
     * The ZIP or other postal code of the shipping address requested by the Cardholder. Length: Maximum 16 characters
     *
     * @return shipAddrPostCode
     **/
    public String getShipAddrPostCode() {
        return shipAddrPostCode;
    }

    public void setShipAddrPostCode(String shipAddrPostCode) {
        this.shipAddrPostCode = shipAddrPostCode;
    }


    /**
     * The state or province of the shipping address associated with the card being used for this purchase. Length: Maximum 3 characters
     *
     * @return shipAddrState
     **/
    public String getShipAddrState() {
        return shipAddrState;
    }

    public void setShipAddrState(String shipAddrState) {
        this.shipAddrState = shipAddrState;
    }


    /**
     * The work phone number provided by the Cardholder.
     *
     * @return workPhone
     **/
    public PhoneNumber getWorkPhone() {
        return workPhone;
    }

    public void setWorkPhone(PhoneNumber workPhone) {
        this.workPhone = workPhone;
    }

    @Override
    public String toString() {
        return "{\n" +
                "\t\t\"billAddrCity\":\"" + billAddrCity + "\",\n" +
                "\t\t\"billAddrCountry\":\"" + billAddrCountry + "\",\n" +
                "\t\t\"billAddrLine1\":\"" + billAddrLine1 + "\",\n" +
                "\t\t\"billAddrLine2\":\"" + billAddrLine2 + "\",\n" +
                "\t\t\"billAddrLine3\":\"" + billAddrLine3 + "\",\n" +
                "\t\t\"billAddrPostCode\":\"" + billAddrPostCode + "\",\n" +
                "\t\t\"billAddrState\":\"" + billAddrState + "\",\n" +
                "\t\t\"cardholderName\":\"" + cardholderName + "\",\n" +
                "\t\t\"email\":\"" + email + "\",\n" +
                "\t\t\"homePhone\":" + homePhone +
                "\t\t\"mobilePhone\":" + mobilePhone +
                "\t\t\"workPhone\":" + workPhone +
                "\t\t\"shipAddrCity\":\"" + shipAddrCity + "\",\n" +
                "\t\t\"shipAddrCountry\":\"" + shipAddrCountry + "\",\n" +
                "\t\t\"shipAddrLine1\":\"" + shipAddrLine1 + "\",\n" +
                "\t\t\"shipAddrLine2\":\"" + shipAddrLine2 + "\",\n" +
                "\t\t\"shipAddrLine3\":\"" + shipAddrLine3 + "\",\n" +
                "\t\t\"shipAddrPostCode\":\"" + shipAddrPostCode + "\",\n" +
                "\t\t\"shipAddrState\":\"" + shipAddrState + "\"\n" +
                "\t},\n";
    }
}

