/*
 * GPayments 3DS Server API Reference
 * Welcome to the 3DS Server RESTful API. You can use our API to access 3DS Server functionalities.  The 3DS Server API is organised around REST. Our API has predictable, resource-oriented URLs, and uses HTTP response codes to indicate API errors. We use built-in HTTP features, such as HTTP authentication and HTTP verbs, which are understood by off-the-shelf HTTP clients. We support cross-origin resource sharing, allowing you to interact securely with our API from a client-side web application (though you should never expose your secret API key in any public website’s client-side code). JSON is returned by all API responses, including errors.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: techsupport@gpayments.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.gpayments.requestor.dto.activeserver;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Information about how the 3DS Requestor authenticated the cardholder before or during the transaction
 */

public class ThreeDSRequestorAuthenticationInfo {

    @JsonProperty("threeDSReqAuthData")
    private String threeDSReqAuthData = null;

    @JsonProperty("threeDSReqAuthMethod")
    private String threeDSReqAuthMethod = null;

    @JsonProperty("threeDSReqAuthTimestamp")
    private String threeDSReqAuthTimestamp = null;

    /**
     * Data that documents and supports a specific authentication process. Length: maximum 2048 bytes, JSON Data Type: String, Value accepted: Any
     *
     * @return threeDSReqAuthData
     **/
    public String getThreeDSReqAuthData() {
        return threeDSReqAuthData;
    }

    public void setThreeDSReqAuthData(String threeDSReqAuthData) {
        this.threeDSReqAuthData = threeDSReqAuthData;
    }

    /**
     * Mechanism used by the Cardholder to authenticate to the 3DS Requestor. Values accepted: [01-99]
     *
     * @return threeDSReqAuthMethod
     **/
    public String getThreeDSReqAuthMethod() {
        return threeDSReqAuthMethod;
    }

    public void setThreeDSReqAuthMethod(String threeDSReqAuthMethod) {
        this.threeDSReqAuthMethod = threeDSReqAuthMethod;
    }

    /**
     * Date and time in UTC of the cardholder authentication. Format accepted: YYYYMMDDHHMM
     *
     * @return threeDSReqAuthTimestamp
     **/
    public String getThreeDSReqAuthTimestamp() {
        return threeDSReqAuthTimestamp;
    }

    public void setThreeDSReqAuthTimestamp(String threeDSReqAuthTimestamp) {
        this.threeDSReqAuthTimestamp = threeDSReqAuthTimestamp;
    }

    @Override
    public String toString() {
        return "{\n" +
                "\t\t\"threeDSReqAuthData\":\"" + threeDSReqAuthData + "\",\n" +
                "\t\t\"threeDSReqAuthMethod\":\"" + threeDSReqAuthMethod + "\",\n" +
                "\t\t\"threeDSReqAuthTimestamp\":\"" + threeDSReqAuthTimestamp + "\"\n" +
                "\t},\n";
    }
}

